name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 关键修复：使用Node.js 18 (LTS)
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          
      # 显式安装PNPM (避免版本冲突)
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      # 修复模块兼容性问题
      - name: Patch module compatibility
        run: |
          echo "{\"type\":\"module\"}" > node_modules/sucrase/package.json
          echo "{\"type\":\"module\"}" > node_modules/@jridgewell/gen-mapping/package.json
          
      - name: Build with Astro
        uses: withastro/action@v3
        with:
          package-manager: pnpm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 